import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Milan Kremic | Senior Full Stack Developer",
  description: "Senior Full Stack Developer with over 10 years of experience in building web applications, including SaaS, CRM, e-commerce, and Fintech platforms. Specialized in JavaScript, PHP, React, Vue, Angular, Node.js, and cloud technologies.",
  keywords: [
    "full stack developer",
    "senior developer",
    "reactjs",
    "vuejs",
    "angular",
    "nextjs",
    "nodejs",
    "javascript",
    "typescript",
    "php",
    "csharp",
    "python",
    "mongodb",
    "postgresql",
    "aws",
    "gcp",
    "docker",
    "ci/cd",
    "saas",
    "crm",
    "e-commerce",
    "fintech",
    "healthcare",
    "iot",
    "portfolio",
    "milan kremic",
  ] as Array<string>,
  authors: {
    name: "Milan Kremic",
    url: "https://linkedin.com/in/milan-kremic-615a4b35a",
  },
} as const;
